name: geomag
description: Translate GPS location data to geo-magnetic data such as magnetic declination.
version: 0.2.0
homepage: https://github.com/jifalops/geomag

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  meta: ^1.0.0

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.5